name: Use Secret in HTTP request

on: push

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Print token (masked)
        run: echo "Użycie sekretu: ${{ secrets.MY_SECRET }}"

      - name: Make fake API request
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://httpbin.org/bearer
